Importing the Libraries and the Dataset

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df=pd.read_csv(r"C:\Learning\Week-01(Python & OOP)\Learning-Curve\Week-4\Day-1\insurance_data.csv")
df.head()

,age,affordibility,bought_insurance
0,22,1,0
1,25,0,0
2,47,1,1
3,52,0,0
4,46,1,1


Splitting into training and testing data

In [3]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df[['age','affordibility']],df.bought_insurance,test_size=0.2,random_state=25)

In [4]:
X_train

,age,affordibility
0,22,1
13,29,0
6,55,0
17,58,1
24,50,1
19,18,1
25,54,1
16,25,0
20,21,1
3,52,0


Data scaling

In [5]:
X_train_scaled= X_train.copy()
X_train_scaled['age']=X_train_scaled['age']/100

X_test_scaled=X_test.copy()
X_test_scaled['age']=X_test_scaled['age']/100


Making the Neural Network using Tensorflow

In [6]:
model= keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,), activation='sigmoid', kernel_initializer='ones',bias_initializer='zeros')
])

c:\Users\PatelDharmikkumar\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [7]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(X_train_scaled,y_train,epochs=5000)

Epoch 1/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 581ms/step - accuracy: 0.5000 - loss: 0.7113
Epoch 2/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.5000 - loss: 0.7110
Epoch 3/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.7106
Epoch 4/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7102
Epoch 5/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.7098
Epoch 6/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.7094
Epoch 7/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.7091
Epoch 8/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.7087
Epoch 9/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.7083
Epoch 10/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.7079
Epoch 11/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.7076
Epoch 12/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy

In [8]:
model.evaluate(X_test_scaled,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step - accuracy: 1.0000 - loss: 0.3550


[0.35497763752937317, 1.0]

In [10]:
model.predict(X_test_scaled) #Anything is more than 0.5,the person will buy the insurance

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step


array([[0.70548475],
       [0.3556957 ],
       [0.16827832],
       [0.4780119 ],
       [0.72606957],
       [0.82949823]], dtype=float32)

In [11]:
coef, intercept= model.get_weights() #get the weights and bias
coef, intercept

(array([[5.0608625],
        [1.408652 ]], dtype=float32),
 array([-2.9137027], dtype=float32))

Calculating the Output using the sigmoid function

In [24]:
def sigmoid(x):
    import math
    return 1/ (1 + np.exp(-x))

In [25]:
def prediction_function(age,affordibility):
    weighted_sum=coef[0]*age+coef[1]*affordibility+intercept
    return sigmoid(weighted_sum)

In [26]:
prediction_function(.47,1)

array([0.7054848], dtype=float32)

Creating a Gradient Descent Function using Python from scratch

In [27]:
def log_loss(y_true,y_prediction):
    epsilon= 1e-15
    y_prediction_new = [max(i,epsilon) for i in y_prediction]
    y_prediction_new = [min(i,1-epsilon) for i in y_prediction_new]
    y_prediction_new = np.array(y_prediction_new)
    return -np.mean(y_true*np.log(y_prediction_new)+(1-y_true)*np.log(1-y_prediction_new))

In [28]:
def sigmoid_numpy(x):
    return 1/(1+np.exp(-x))
sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [31]:
def gradient_descent(age,affordibility,y_true,epochs):
    #Will return w1,w2,bias
    w1 = w2 = 1
    bias = 0
    learning_rate= 0.5
    n=len(age)
    
    
    for i in range(epochs):
        weighted_sum=w1 * age + w2 + affordibility + bias
        y_predicted=sigmoid_numpy(weighted_sum)
        loss = log_loss(y_true,y_predicted)

        w1d=(1/n)*np.dot(np.transpose(age),(y_predicted-y_true))
        w2d=(1/n)*np.dot(np.transpose(affordibility),(y_predicted-y_true))
        bias_d=np.mean(y_predicted-y_true)

        w1=w1-learning_rate*w1d
        w2=w2-learning_rate*w2d
        bias = bias - learning_rate*bias_d
        
        print(f"Epoch:{i},w1:{w1},w1:{w2},bias:{bias},loss:{loss}")    

    return w1,w2,bias

In [32]:
gradient_descent(X_train_scaled['age'],X_train_scaled['affordibility'],y_train,1000)

Epoch:0,w1:0.9468767520411948,w1:0.9124306539072167,bias:-0.18674437612074016,loss:1.018275378338316
Epoch:1,w1:0.9003992424826611,w1:0.8328619790035016,bias:-0.35610837393092587,loss:0.9151313088294404
Epoch:2,w1:0.8611607698648571,w1:0.7623243182121827,bias:-0.5067102255893514,loss:0.8313655700781569
Epoch:3,w1:0.8293504287323638,w1:0.7013936907883399,bias:-0.6382200255426729,loss:0.7660995888503931
Epoch:4,w1:0.8047481556654444,w1:0.6501109849169785,bias:-0.7513391587448974,loss:0.7171711077184072
Epoch:5,w1:0.786806749391703,w1:0.6080248362899263,bias:-0.8475677107984416,loss:0.681674754165525
Epoch:6,w1:0.7747771952217023,w1:0.5743242735490958,bias:-0.9288771489254919,loss:0.6565639106999182
Epoch:7,w1:0.7678307826101037,w1:0.5480002388519579,bias:-0.9974037061572257,loss:0.6390946393221831
Epoch:8,w1:0.7651509022988786,w1:0.5279865960766613,bias:-1.0552248823146255,loss:0.627039684763143
Epoch:9,w1:0.7659886741843248,w1:0.5132586726102851,bias:-1.104228562675286,loss:0.6187182660

(np.float64(7.08262420539592),
 np.float64(7.239226305953864),
 np.float64(-10.677482876578793))